### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jhawlc** [11148333/11148333.github.io#7]
Test your website in the following environments:

1. Chrome
2. Firefox
3. Edge
4. Mobile phone

For each environment, check that 

- Navigation links work, 
- pictures work, 
- contact form works
- pages are responsive

Use Steps Recorder to document this

**Comment by 11148333** [comment]
[screenshots.zip](https://github.com/11148333/11148333.github.io/files/11564117/screenshots.zip)

**Comment by 11148333** [comment]
[screenshots.zip](https://github.com/11148333/11148333.github.io/files/11565231/screenshots.zip)
