### ISSUE TITLE
Purpose Document

### ISSUE THREAD

**Issue by jhawlc** [11148333/11148333.github.io#8]
Write a report to explain how your website meets the purpose set in the assignment: 

'You are going to create an interactive multimedia website about your favourite wearable technology
that you can share with your friends and family and educate them. Include 4-5 different types of
wearable technologies in your website. The website must have a Home Page and a Contact Us page .
You should dedicate one page per technology.'

1. Is your website interactive?
2. Does your website have multimedia?
3. Have you included 4-5 different types of technology?
4. Does your website have a contact page?
5. Does your website have a hompage?
6. Are you able to share the site with your friends and family?
7. Write about each point and explain how your website does this.

**Comment by 11148333** [comment]
your website interactive?
- Yes I have given all the evidence
Does your website have multimedia?
- Yes I have add some images and video 
Have you included 4-5 different types of technology?
-I have use 4 types of technology Head ,Feet ,Arm and clothing.
Does your website have a contact page?
- Yes my website have contact page.
Does your website have a homepage?
- Yes, I have homepage in my website 
Are you able to share the site with your friends and family?
- Yes I can share my website to my friends and family.
